[env]
TERM = "alacritty"

[font]
size = 16.0

[mouse]
hide_when_typing = true

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0017"
key = "D"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "E"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi"
mods = "Control"

[terminal.shell]
args = ["-l", "-c", "/bin/tmux"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8

[window.padding]
x = 10
y = 13

[general]
live_config_reload = true
import = ["/home/kemshim/.config/alacritty/themes/themes/onedark.toml"]

[terminal]
