ipc = on
splash = false

preload = /home/kemshim/Pictures/wallpaper/wallpaper02.jpg
wallpaper = DP-1,/home/kemshim/Pictures/wallpaper/wallpaper02.jpg
wallpaper = ,/home/kemshim/Pictures/wallpaper/wallpaper02.jpg
