## highlight
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_show_sync_mode 'on'


## tmux-ssh-split
set-option -g @ssh-split-h-key '|'
set-option -g @ssh-split-v-key '_'
set-option -g @ssh-split-keep-cwd "true"
set-option -g @ssh-split-keep-remote-cwd "true"
set-option -g @ssh-split-strip-cmd "true"
set-option -g @ssh-split-verbose "true"
set-option -g @ssh-split-debug "true"

## status bar — set AFTER catppuccin loads
set -g status-style "bg=#0f0f18"
set -g status-left ''
set -g status-right "#[fg=#342d44,bg=#0f0f18]▐#[fg=#5a4b71,bg=#342d44]▐#[fg=#7f699d,bg=#5a4b71]▐#[fg=#a587ca,bg=#7f699d]▐#[fg=#cba6f7,bg=#a587ca]▐#[fg=#0f0f18,bg=#cba6f7,bold] #S "
set -g status-left-length 100
set -g status-right-length 100

# ▐▌ half-block gradient tabs
set -g window-status-format "#[fg=#cdd6f4,bg=#0f0f18] #W "
set -g window-status-current-format "#[fg=#6e5b89,bg=#0f0f18]▐#[fg=#9c80c0,bg=#6e5b89]▐#[fg=#cba6f7,bg=#9c80c0]▐#[fg=#0f0f18,bg=#cba6f7,bold,italics] #W #[fg=#cba6f7,bg=#9c80c0]▌#[fg=#9c80c0,bg=#6e5b89]▌#[fg=#6e5b89,bg=#0f0f18]▌"
set -g window-status-separator ""

## tmux-sessionx
# I recommend using `o` if not already in use, for least key strokes when launching
set -g @sessionx-bind 'o'
