## highlight
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_show_sync_mode 'on'


## tmux-ssh-split
set-option -g @ssh-split-h-key '|'
set-option -g @ssh-split-v-key '_'
set-option -g @ssh-split-w-key 'c'
set-option -g @ssh-split-keep-cwd "true"
set-option -g @ssh-split-keep-remote-cwd "true"
set-option -g @ssh-split-no-shell "true"
set-option -g @ssh-split-strip-cmd "true"
set-option -g @ssh-split-verbose "true"
set-option -g @ssh-split-debug "true"

## tmux-claude
set -g @claude-launch-key 'a'
set -g @claude-resume-key 'A'
set -g @claude-switch-key 'O'

## tmux-sessionx
# I recommend using `o` if not already in use, for least key strokes when launching
set -g @sessionx-bind 'o'
