## status bar — set AFTER catppuccin loads
set -g status-style "bg=#0f0f18"
set -g status-left ''
set -g status-right "#[fg=#342d44,bg=#0f0f18]▐#[fg=#5a4b71,bg=#342d44]▐#[fg=#7f699d,bg=#5a4b71]▐#[fg=#a587ca,bg=#7f699d]▐#[fg=#cba6f7,bg=#a587ca]▐#[fg=#0f0f18,bg=#cba6f7,bold] #S "
set -g status-left-length 100
set -g status-right-length 100

## pane styling
set -g pane-border-lines heavy
set -g pane-active-border-style 'fg=#cba6f7'
set -g pane-border-style 'fg=colour237'
set -g window-active-style 'bg=default,fg=#ffffff'
set -g window-style 'bg=default,fg=colour246'

## popup window
set -g popup-style 'bg=default'
set -g popup-border-style 'fg=default'

# ▐▌ half-block gradient tabs
set -g window-status-format "#[fg=#cdd6f4,bg=#0f0f18] #W "
set -g window-status-current-format "#[fg=#6e5b89,bg=#0f0f18]▐#[fg=#9c80c0,bg=#6e5b89]▐#[fg=#cba6f7,bg=#9c80c0]▐#[fg=#0f0f18,bg=#cba6f7,bold,italics] #W #[fg=#cba6f7,bg=#9c80c0]▌#[fg=#9c80c0,bg=#6e5b89]▌#[fg=#6e5b89,bg=#0f0f18]▌"
set -g window-status-separator ""
