## my settings
# OS が Darwin の時は pbcopy を使う
if-shell -b '[ "$(uname)" = "Darwin" ]' {
  set -s copy-command "pbcopy"
}

# true color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-kitty:RGB"
set -a terminal-features ',xterm-kitty:RGB'

# clipboard
set -g set-clipboard on
set -g allow-passthrough all

# Forward kitty environment variables into tmux sessions
set -ga update-environment "TERM"
set -ga update-environment "TERM_PROGRAM"
set -ga update-environment "KITTY_PID"
set -ga update-environment "KITTY_WINDOW_ID"
set -ga update-environment "SNACKS_KITTY"

# my prefix
unbind C-b
set -g prefix C-t
set -g mouse on
setw -g mode-keys vi
set -g renumber-windows on
set -g status-position bottom

## tmux plugin manager
TMUX_PLUGIN_MANAGER_PATH="~/.local/share/tmux/plugins"

# load other plugins settings
source "~/.config/tmux/plugins.conf"
source "~/.config/tmux/keyconfig.conf"
source "~/.config/tmux/style.conf"

# plugins (TPM)
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'pschmitt/tmux-pain-control'
set -g @plugin 'KEMSHlM/tmux-ssh-split'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tpm'

run "${TMUX_PLUGIN_MANAGER_PATH}/tpm/tpm"
